
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: scheduling_development

test:
  <<: *default
  database: scheduling_test

production:
  <<: *default
  database: scheduling_production
  username: scheduling
  password: <%= ENV['SCHEDULING_DATABASE_PASSWORD'] %>
